// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'close'
  | 'empty-value'
  | 'no-edge'
  | 'scan-current-view'
  | 'scan-empty'
  | 'scan-found'
  | 'scan-no-edit'
  | 'scan-no-items'
  | 'scan-no-view'
  | 'scan-progress'
  | 'scan-title'
  | 'search-by-title'
  | 'skip'
  | 'workflow-finished'
  | 'workflow-finished-detail'
  | 'workflow-hint';
